# This is our "Source of Truth" file.
# Variables defined here apply to all hosts in our inventory.

# --- Installation Mode Control ---
# Set this to true to install into a user's home directory without sudo.
hadoop_install_no_sudo: true

# --- Versioning and Installation ---

hadoop_version: "3.3.6"
hadoop_url: "https://archive.apache.org/dist/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
hadoop_checksum: "sha256:f5195059c0d4102adaa7fff17f7b2a85df906bcb6e19948716319f9978641a04"

# --- User and Path Configuration (Now Dynamic!) ---
# ansible_user_dir is a "fact" that automatically resolves to the remote user's home directory.
hadoop_user_home_dir: "{{ ansible_user_dir }}/hadoop_installs"

# Define the installation prefix based on the mode.
install_prefix: "{{ hadoop_user_home_dir if hadoop_install_no_sudo else '/opt' }}"

# The symlink that points to the active installation.
hadoop_symlink: "{{ install_prefix }}/hadoop"

# System user to own the hadoop files (only used in sudo mode).
hadoop_user: "hadoop"
hadoop_group: "hadoop"

# --- Dependency Management ---
java_package: "openjdk-11-jdk"

# --- Configuration ---
namenode_host: "{{ hostvars[groups['namenode'][0]]['ansible_host'] | default(groups['namenode'][0]) }}"

# Define data directories based on the installation mode.
namenode_data_dir: "{{ install_prefix }}/data/namenode"
datanode_data_dir: "{{ install_prefix }}/data/datanode"
